package Stages;

public enum SceneEnums {
    PRIMARY_SCENE, CREDIT_SCREEN, GAME_SELECT, CRZ_RUM_CTRL_SCREEN, CRZ_RHY_CTRL_SCREEN, RUM_CHAR_SELECT, RUM_GAME, RHY_SONG_SELECT, RHY_GAME, RHY_END_SCREEN
}
